# Generated by Django 6.1.1 on 2026-09-17 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('tailors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='shop_name',
        ),
        migrations.AddField(
            model_name='design',
            name='category',
            field=models.CharField(choices=[('Panjabi', 'Panjabi'), ('Shirt', 'Shirt'), ('Blouse', 'Blouse'), ('Suit', 'Suit')], default='Shirt', max_length=50),
        ),
        migrations.AddField(
            model_name='design',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], default='Male', max_length=20),
        ),
        migrations.AddField(
            model_name='design',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='design',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='tailors.tailorshop'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='approval_status',
            field=models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending Approval', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Tailor', 'Tailor'), ('Rider', 'Rider'), ('Admin', 'Admin')], default='Customer', max_length=20),
        ),
    ]
