# Generated by Django 6.1.1 on 2026-09-13 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='category',
        ),
        migrations.RemoveField(
            model_name='design',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='design',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='design',
            name='shop_name',
        ),
        migrations.AddField(
            model_name='design',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='designs/'),
        ),
        migrations.AlterField(
            model_name='design',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='design',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Customer', 'Customer'), ('Tailor', 'Tailor'), ('Rider', 'Rider')], default='Customer', max_length=20)),
                ('shop_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
