# Generated by Django 6.1.1 on 2026-09-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_userprofile_shop_name_design_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='driving_license',
            field=models.FileField(blank=True, null=True, upload_to='private/rider_licenses/'),
        ),
    ]
