# Generated by Django 6.1.1 on 2026-09-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_campaign_clothingcategory_commissionrule_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={},
        ),
        migrations.AlterModelOptions(
            name='commissionrule',
            options={},
        ),
        migrations.AlterModelOptions(
            name='deliverychargerule',
            options={},
        ),
        migrations.RemoveField(
            model_name='measurementcategory',
            name='description',
        ),
        migrations.AddField(
            model_name='campaign',
            name='audience',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='campaign',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='campaigns/'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='promo_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='commissionrule',
            name='minimum_commission',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
        ),
        migrations.AddField(
            model_name='commissionrule',
            name='premium_rate',
            field=models.DecimalField(decimal_places=2, default=7, max_digits=5),
        ),
        migrations.AddField(
            model_name='commissionrule',
            name='rider_payout_share',
            field=models.DecimalField(decimal_places=2, default=80, max_digits=5),
        ),
        migrations.AddField(
            model_name='deliverychargerule',
            name='extra_km_charge',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=10),
        ),
        migrations.AddField(
            model_name='deliverychargerule',
            name='fabric_pickup_charge',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=10),
        ),
        migrations.AddField(
            model_name='measurementcategory',
            name='fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='measurementcategory',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], default='Unisex', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commissionrule',
            name='name',
            field=models.CharField(default='Platform Commission', max_length=100),
        ),
        migrations.AlterField(
            model_name='commissionrule',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
        migrations.AlterField(
            model_name='deliverychargerule',
            name='charge',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='deliverychargerule',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=150, max_digits=10),
        ),
        migrations.AlterField(
            model_name='deliverychargerule',
            name='name',
            field=models.CharField(default='Default Delivery Rule', max_length=100),
        ),
    ]
