# Generated by Django 6.1.1 on 2026-09-17 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalMeasurementField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('shop_name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DesignCustomizationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('shop_name', models.CharField(max_length=150)),
                ('required_fields', models.ManyToManyField(to='customers.globalmeasurementfield')),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relation', models.CharField(choices=[('Self', 'Myself'), ('Family', 'Family Member')], default='Self', max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], default='Male', max_length=10)),
                ('category', models.CharField(max_length=50)),
                ('values', models.JSONField(blank=True, default=dict, help_text='Stores measurements dynamically, e.g. {"Chest": "40", "Shoulder": "18"}')),
                ('is_default', models.BooleanField(default=False)),
                ('updated', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('product_name', models.CharField(max_length=150)),
                ('shop_name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('In Production', 'In Production'), ('Ready', 'Ready'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateField(auto_now_add=True)),
                ('fabric_source', models.CharField(choices=[('shop', 'Shop Fabric'), ('own', 'Own Fabric')], default='shop', max_length=10)),
                ('pickup_address', models.TextField(blank=True, null=True)),
                ('pickup_status', models.CharField(blank=True, choices=[('Pickup Requested', 'Pickup Requested'), ('Rider Assigned', 'Rider Assigned'), ('Fabric Collected', 'Fabric Collected'), ('Fabric Delivered to Tailor Shop', 'Fabric Delivered to Tailor Shop')], max_length=50, null=True)),
                ('rider_name', models.CharField(blank=True, max_length=100, null=True)),
                ('trial_requested', models.BooleanField(default=False)),
                ('trial_status', models.CharField(blank=True, choices=[('Requested', 'Requested'), ('Scheduled', 'Scheduled'), ('Completed', 'Completed')], max_length=20, null=True)),
                ('trial_date', models.DateTimeField(blank=True, null=True)),
                ('profile_name_snapshot', models.CharField(blank=True, max_length=100, null=True)),
                ('measurement_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.measurementprofile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
