# Generated by Django 6.1.1 on 2026-09-17 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='fabric_source',
            field=models.CharField(default='shop', max_length=10),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='measurement_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.measurementprofile'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='pickup_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='trial_requested',
            field=models.BooleanField(default=False),
        ),
    ]
