# Generated by Django 6.1.1 on 2026-09-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_cartitem_fabric_source_cartitem_measurement_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_pin',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
