# Generated by Django 6.1 on 2026-08-31 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chest', models.DecimalField(decimal_places=2, help_text='Inches', max_digits=5)),
                ('waist', models.DecimalField(decimal_places=2, help_text='Inches', max_digits=5)),
                ('shoulders', models.DecimalField(decimal_places=2, help_text='Inches', max_digits=5)),
                ('sleeve_length', models.DecimalField(decimal_places=2, help_text='Inches', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='customers.measurementprofile')),
            ],
        ),
    ]
