# Generated by Django 6.1.1 on 2026-09-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailorshop',
            name='trade_license',
            field=models.FileField(blank=True, null=True, upload_to='private/tailor_licenses/'),
        ),
    ]
